name: Publish PDF from Markdown
on:
  push:
    branches:
      - main
    paths:
      - 'o11y2022_sponsor_guide**.md'
  pull_request:
    branches:
      - main
    paths:
      - 'o11y2022_sponsor_guide**.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert Markdown into HTML and PDF
        uses: KoharaKazuya/marp-cli-action@v1
        with:
          generate-html: "false"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: sponsor_guide
        
          
